### ISSUE TITLE
No binaries on bintray?

### ISSUE THREAD

**Issue by msabramo** [grundic/teamcity-avatar#7]
I may be overlooking something but I don't actually see a download available at https://bintray.com/grundic/generic/teamcity-avatar/1.3/view

<img width="1026" alt="screen shot 2015-11-08 at 2 38 32 pm" src="https://cloud.githubusercontent.com/assets/305268/11023185/99ca103e-8626-11e5-9d04-39088c345ee3.png">

**Comment by grundic** [comment]
Hi, @msabramo,
Sorry for late answer, got a little bit busy :(
Have you tried to select Files tab? I suppose you could find releases there.
Hope it helps.

**Comment by msabramo** [comment]
Oops. Yes, you are correct.

<img width="992" alt="screen shot 2015-11-23 at 8 25 12 am" src="https://cloud.githubusercontent.com/assets/305268/11342361/d9743048-91bb-11e5-806d-4e4199e8f2da.png">

Sorry!
